---
- name: Setup Development Environment
  hosts: localhost
  vars:
    os: "{{ ansible_os_family | lower }}"
    config_path: "{{ lookup('env', 'HOME') }}/configurations"
    src_key: "./ssh/id_ed25519_vault"
    dest_key: "{{ lookup('env', 'HOME') }}/.ssh/id_ed25519"
    nvim_archive: "{{ 'nvim-linux-arm64.tar.gz' if ansible_architecture == 'aarch64' else 'nvim-linux-x86_64.tar.gz' }}"
  tasks:
    - name: Set timezone
      become: true
      community.general.timezone:
        name: America/Los_Angeles
    - name: install ssh 
      ansible.builtin.include_tasks: "tasks/ssh.yml"
      tags:
        - dotfiles
        - ssh
        - git
    # Currently, using mise. Remove it after a while if that works good.
    # - name: setup rust 
    #   ansible.builtin.include_tasks: "tasks/setup_rust.yml"
    #   tags:
    #     - rust 
    - name: Install git repositories
      ansible.builtin.include_tasks: "tasks/setup_git_and_repos.yml" 
      tags: 
        - git
        - dotfiles
    - name: Link dotfiles
      ansible.builtin.include_tasks: "tasks/link_dotfiles.yml"
      tags: 
        - dotfiles
    - name: Link Scripts
      ansible.builtin.include_tasks: "tasks/link_scripts.yml"
      tags: 
        - dotfiles 
    - name: Include OS specific tasks
      ansible.builtin.include_tasks: "tasks/{{ os }}_tasks.yml"
      tags: 
        - os
    - name: Include Linux Tasks 
      ansible.builtin.include_tasks: "tasks/linux_tasks.yml"
      when: >
        ansible_facts['os_family'] in ['Debian', 'RedHat', 'Archlinux', 'Alpine']
      tags: 
        - os
    - name: Include Common OS Tasks 
      ansible.builtin.include_tasks: "tasks/common_os_tasks.yml"
      tags: 
        - os
    - name: Setup Amazon Work 
      ansible.builtin.include_tasks: "tasks/amazon.yml"
      tags: 
        - amazon 
#    - name: Enable fzf-tab 
#      shell: |
#        source ~/.zshrc && enable-fzf-tab
#      args:
#        executable: /bin/zsh
#      tags:
#        - fzf
    - name: Setup Fonts 
      ansible.builtin.include_tasks: "tasks/fonts.yml"
      tags: 
        - fonts 
