---
- name: Setup Development Environment
  hosts: localhost
  vars:
    os: "{{ ansible_os_family | lower }}"
    config_path: "~/configurations"
    src_key: "./ssh/id_ed25519_vault"
    dest_key: "{{ lookup('env', 'HOME') }}/.ssh/id_ed25519"
  tasks:
    - name: Install SSH 
      ansible.builtin.include_tasks: "tasks/ssh.yml"
      tags:
        - dotfiles
        - install
        - ssh
    - name: Install git repositories
      ansible.builtin.include_tasks: "tasks/setup_git_and_repos.yml" 
      tags: 
        git 
        install
        dotfiles
#    - name: Link dotfiles
#      ansible.builtin.include_tasks: link_dotfiles.yml
#      tags: dotfiles
#    - name: Include OS specific tasks
#      ansible.builtin.include_tasks: "{{ os }}_tasks.yml"
#      tags: os_specific
#    - name: Setup cron job
#      ansible.builtin.include_tasks: cron.yml
#      tags: cron
#
