---
- name: Setup Development Environment
  hosts: localhost
  vars:
    os: "{{ ansible_os_family | lower }}"
    config_path: "{{ lookup('env', 'HOME') }}/configurations"
    src_key: "./ssh/id_ed25519_vault"
    dest_key: "{{ lookup('env', 'HOME') }}/.ssh/id_ed25519"
  tasks:
    - name: install ssh 
      ansible.builtin.include_tasks: "tasks/ssh.yml"
      tags:
        - dotfiles
        - ssh
        - git
    - name: setup rust 
      ansible.builtin.include_tasks: "tasks/setup_rust.yml"
      tags:
        - rust 
        - packages
    - name: Include OS specific tasks
      ansible.builtin.include_tasks: "tasks/{{ os }}_tasks.yml"
      tags: 
        - os
    - name: Install git repositories
      ansible.builtin.include_tasks: "tasks/setup_git_and_repos.yml" 
      tags: 
        - git 
        - dotfiles
    - name: Link dotfiles
      ansible.builtin.include_tasks: "tasks/link_dotfiles.yml"
      tags: 
        - dotfiles
    - name: Link Scripts
      ansible.builtin.include_tasks: "tasks/link_scripts.yml"
      tags: 
        - scripts 
    - name: Setup Amazon Work 
      ansible.builtin.include_tasks: "tasks/amazon.yml"
      tags: 
        - amazon 
    - name: Setup Fonts 
      ansible.builtin.include_tasks: "tasks/fonts.yml"
      tags: 
        - fonts 
#    - name: Setup cron job
#      ansible.builtin.include_tasks: cron.yml
#      tags: cron
#
