- name: Ensure work directory exists
  file:
    dest: "{{ lookup('env', 'HOME') }}/work"
    state: directory
  tags:
    - always
- name: Ensure .aws directory exists
  file:
    dest: "{{ lookup('env', 'HOME') }}/.aws"
    state: directory
  tags:
    - always
- name: Create ~/.aws/config file with specific content
  ansible.builtin.copy:
    dest: "{{ lookup('env', 'HOME') }}/.aws/config"
    content: |
      [profile default]
      s3 =
        preferred_transfer_client=crt
        target_bandwidth=100Gb/s
  tags:
    - always

- name: Install AWS CLI v2
  shell: |
    cd /tmp
    curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
    unzip awscliv2.zip
    sudo ./aws/install
    rm -rf awscliv2.zip aws
  args:
    creates: /usr/local/bin/aws
  tags:
    - always
