- name: Install Apt Packages
  apt:
    name:
      - zsh
      - tmux
      - cmake
      - npm
      - gcc
      - g++
      - ripgrep
      - make
      - python3-pip
      - python3-venv
      - python3-boto3
      - unzip
      - maven
      - nload
    state: present
    update_cache: yes
  become: yes
  tags: always
- name: Change shell to zsh
  user:
    name: "{{ ansible_env.USER }}"
    shell: /bin/zsh
  become: yes
  tags: always
