- name: Install ZSH
  apt: name=zsh
  tags:
    - install
    - zsh
- name: Change shell to zsh
  shell: chsh -s $(which zsh)
  tags:
    - install
    - zsh
- name: Ensure gnupg is installed #adding neovim ppa requires it
  apt:
    name: gnupg
    state: present
- name: Add the Neovim PPA
  apt_repository:
    repo: ppa:neovim-ppa/stable
    state: present
  become: yes

- name: Update apt cache
  apt:
    update_cache: yes
    become: yes

- name: Install Neovim
  apt:
    name: neovim
    state: latest
    become: yes

- name: Install tmux
  apt:
    name: tmux
    state: latest
    become: yes

