- name: Install Apt Packages
  apt:
    name:
      - zsh
      - gnupg #adding neovim ppa requires it
      - tmux
      - cmake
      - npm
      - gcc
      - g++
      - ripgrep
      - make
      - python3-pip
      - python3-venv
      - python3-boto3
      - unzip
      - maven
    state: present
    update_cache: yes
  become: yes
  tags: always
- name: Change shell to zsh
  user:
    name: "{{ ansible_env.USER }}"
    shell: /bin/zsh
  become: yes
  tags: always
- name: Setup Neovim from Source
  ansible.builtin.include_tasks: "setup_nvim_from_source.yml"
  tags: always
- name: Setup fzf from Source
  ansible.builtin.include_tasks: "setup_fzf_from_source.yml"
  tags: always
