- name: Install Apt Packages 
  apt: 
    name: 
      - zsh
      - gnupg #adding neovim ppa requires it
      - tmux
      - cmake
      - cargo
      - npm
      - gcc
      - g++
      - ripgrep
      - make
  tags:
    - package 
    - zsh
    - nvim
- name: Change shell to zsh
  shell: chsh -s $(which zsh)
  tags:
    - zsh
- name: Add the Neovim PPA
  apt_repository:
    repo: ppa:neovim-ppa/unstable
    state: present
  tags: nvim
- name: Update apt cache
  apt:
    update_cache: yes
  tags: nvim
- name: Install Neovim
  apt:
    name: neovim
    state: latest
  tags: nvim
- name: Install fzf 
  shell: |
    git clone --depth 1 https://github.com/junegunn/fzf.git {{ lookup('env', 'HOME') }}/.fzf
    {{ lookup('env', 'HOME') }}/.fzf/install --all
  args:
    creates: "{{ lookup('env', 'HOME') }}/.fzf"
  tags:
    - fzf
    - packages
- name: Check if ripgrep is already installed
  command: rg --version
  register: rg_version
  ignore_errors: yes
  changed_when: false
  tags:
    - ripgrep
- name: Clone ripgrep repository
  git:
    repo: 'https://github.com/BurntSushi/ripgrep.git'
    dest: "{{ lookup('env', 'HOME') }}/ripgrep"
    update: no
  when: rg_version.rc != 0
  tags:
    - ripgrep
- name: Build ripgrep from source
  shell: |
    cd {{ lookup('env', 'HOME') }}/ripgrep && cargo build --release
  args:
    creates: "{{ lookup('env', 'HOME') }}/ripgrep/target/release/rg"
  when: rg_version.rc != 0
  tags:
    - ripgrep
- name: Copy ripgrep binary to /usr/local/bin
  copy:
    src: "{{ lookup('env', 'HOME') }}/ripgrep/target/release/rg"
    dest: /usr/local/bin/rg
    mode: '0755'
  when: rg_version.rc != 0
  tags:
    - ripgrep
