- name: Install Apt Packages 
  apt: 
    name: 
      - zsh
      - gnupg #adding neovim ppa requires it
      - tmux
      - cmake
      - cargo
      - npm
      - gcc
      - g++
  tags:
    - package 
    - zsh
    - nvim
- name: Change shell to zsh
  shell: chsh -s $(which zsh)
  tags:
    - zsh
- name: Add the Neovim PPA
  apt_repository:
    repo: ppa:neovim-ppa/unstable
    state: present
  tags: nvim
- name: Update apt cache
  apt:
    update_cache: yes
  tags: nvim
- name: Install Neovim
  apt:
    name: neovim
    state: latest
  tags: nvim
