- name: Install Apt Packages 
  apt: 
    name: 
      - zsh
      - gnupg #adding neovim ppa requires it
      - tmux
      - cmake
      - cargo
      - npm
      - gcc
      - g++
      - ripgrep
      - make
  tags:
    - package 
    - zsh
    - nvim
- name: Change shell to zsh
  user:
    name: "{{ ansible_env.USER }}"
    shell: /bin/zsh
  tags:
    - zsh
  become: yes
- name: Add the Neovim PPA
  apt_repository:
    repo: ppa:neovim-ppa/unstable
    state: present
  tags: nvim
- name: Update apt cache
  apt:
    update_cache: yes
  tags: nvim
- name: Install Neovim
  apt:
    name: neovim
    state: latest
  tags: nvim
- name: Install fzf 
  shell: |
    git clone --depth 1 https://github.com/junegunn/fzf.git {{ lookup('env', 'HOME') }}/.fzf
    {{ lookup('env', 'HOME') }}/.fzf/install --all
  args:
    creates: "{{ lookup('env', 'HOME') }}/.fzf"
  tags:
    - fzf
    - packages
