- name: Install Apt Packages 
  apt: 
    name: 
      - zsh
      - gnupg #adding neovim ppa requires it
      - tmux
      - cmake
      - npm
      - gcc
      - g++
      - ripgrep
      - make
- name: Change shell to zsh
  user:
    name: "{{ ansible_env.USER }}"
    shell: /bin/zsh
  become: yes
- name: Add the Neovim PPA
  apt_repository:
    repo: ppa:neovim-ppa/unstable
    state: present
- name: Update apt cache
  apt:
    update_cache: yes
- name: Install Neovim
  apt:
    name: neovim
    state: latest
- name: Setup fzf from Source 
  ansible.builtin.include_tasks: "setup_fzf_from_source.yml"
