---
- name: Link .zshrc
  shell: "ln -s {{ config_path }}/dotfiles/zshrc {{ lookup('env', 'HOME') }}/.zshrc"
- name: Link Neovim configuration
  shell: "ln -s {{ config_path }}/nvim {{ lookup('env', 'HOME') }}/.config/nvim"
- name: Link tmux.conf
  shell: "ln -s {{ config_path }}/dotfiles/tmux.conf {{ lookup('env', 'HOME') }}/.tmux.conf"
- name: Link p10k.zsh
  shell: "ln -s {{ config_path }}/dotfiles/p10k.zsh {{ lookup('env', 'HOME') }}/.p10k.zsh"

