---
- name: Ensure ~/.config directory exists
  file:
    dest: "{{ lookup('env', 'HOME') }}/.config"
    state: directory
  tags: always
- name: Ensure ~/.config/ghostty directory exists
  file:
    dest: "{{ lookup('env', 'HOME') }}/.config/ghostty"
    state: directory
  tags: always
- name: Ensure ~/.claude directory exists
  file:
    dest: "{{ lookup('env', 'HOME') }}/.claude"
    state: directory
  tags: always
# - name: Ensure ~/.config/mise directory exists
#   file:
#     dest: "{{ lookup('env', 'HOME') }}/.config/mise"
#     state: directory
#   tags: always

- name: Link Ghostty configuration
  ansible.builtin.file:
    src: "{{ config_path }}/dotfiles/ghostty-config"
    dest: "{{ lookup('env', 'HOME') }}/.config/ghostty/config"
    state: link
    force: yes
  tags: always
- name: Link Neovim configuration
  ansible.builtin.file:
    src: "{{ config_path }}/nvim"
    dest: "{{ lookup('env', 'HOME') }}/.config/nvim"
    state: link
    force: yes
  tags: always
- name: Link tmux.conf
  ansible.builtin.file:
    src: "{{ config_path }}/dotfiles/tmux.conf"
    dest: "{{ lookup('env', 'HOME') }}/.tmux.conf"
    state: link
    force: yes
  tags: always
- name: Link p10k.zsh
  ansible.builtin.file:
    src: "{{ config_path }}/dotfiles/p10k.zsh"
    dest: "{{ lookup('env', 'HOME') }}/.p10k.zsh"
    state: link
    force: yes
  tags: always
- name: Link .zshrc
  ansible.builtin.file:
    src: "{{ config_path }}/dotfiles/zshrc"
    dest: "{{ lookup('env', 'HOME') }}/.zshrc"
    state: link
    force: yes
  tags: always

- name: Link .gitconfig
  ansible.builtin.file:
    src: "{{ config_path }}/dotfiles/gitconfig"
    dest: "{{ lookup('env', 'HOME') }}/.gitconfig"
    state: link
    force: yes
  tags: always

- name: Link .gitignore
  ansible.builtin.file:
    src: "{{ config_path }}/dotfiles/gitignore_global"
    dest: "{{ lookup('env', 'HOME') }}/.gitignore_global"
    state: link
    force: yes
  tags: always

- name: Link claude code
  ansible.builtin.file:
    src: "{{ config_path }}/dotfiles/claude_code_settings.json"
    dest: "{{ lookup('env', 'HOME') }}/.claude/settings.json"
    state: link
    force: yes
  tags: always

# - name: Link mise config 
#   ansible.builtin.file:
#     src: "{{ config_path }}/dotfiles/mise_config.toml"
#     dest: "{{ lookup('env', 'HOME') }}/.config/mise/config.toml"
#     state: link
#     force: yes
#   tags: always
