- name: Install required packages 
  yum:
    name:
      - "@Development tools"
      - cmake
      - python3-devel
      - python3-pip
      - zsh
      - tmux
      - cargo
      - npm
      - gcc
      - g++
- name: Change shell to zsh
  shell: chsh -s $(which zsh)
  tags:
    - install
    - zsh
- name: Upgrade pip and install Neovim package for Python
  pip:
    name: neovim
    state: latest
  tags:
    - nvim
- name: Clone Neovim repository
  git:
    repo: 'https://github.com/neovim/neovim.git'
    dest: '/tmp/neovim'
    update: yes
  tags:
    - nvim
- name: Build Neovim from source
  command: make CMAKE_BUILD_TYPE=Release -j
  args:
    chdir: /tmp/neovim
  tags:
    - nvim
- name: Install Neovim
  command: make install
  args:
    chdir: /tmp/neovim
    creates: /usr/local/bin/nvim
  tags:
    - nvim

- name: Install fzf 
  shell: |
    git clone --depth 1 https://github.com/junegunn/fzf.git {{ lookup('env', 'HOME') }}/.fzf
    {{ lookup('env', 'HOME') }}/.fzf/install --all
  args:
    creates: "{{ lookup('env', 'HOME') }}/.fzf"
  tags:
    - fzf
    - packages

