- name: Install required packages
  yum:
    name:
      - "@Development tools"
      - python3-devel
      - python3-pip
      - cmake
      - zsh
      - npm
      - gcc
      - g++
      - gdb
      - util-linux-user #chsh requires it
      - maven
      - ninja-build
      - ccache
    state: present
  become: yes
  tags: always
- name: Install boto3 with pip3
  pip:
    name: boto3
    executable: pip3
  become: yes
  tags: always
- name: Change shell to zsh
  user:
    name: "{{ ansible_env.USER }}"
    shell: /bin/zsh
  become: yes
  tags: always
