- name: Install required packages 
  yum:
    name:
      - "@Development tools"
      - cmake
      - python3-devel
      - python3-pip
      - zsh
      - tmux
      - npm
      - gcc
      - g++
      - util-linux-user #chsh requires it
    state: present
  become: yes
- name: Change shell to zsh
  user:
    name: "{{ ansible_env.USER }}"
    shell: /bin/zsh
  become: yes
- name: Setup Neovim from Source 
  ansible.builtin.include_tasks: "setup_neovim_from_source.yml"
- name: Install fzf 
  shell: |
    git clone --depth 1 https://github.com/junegunn/fzf.git {{ lookup('env', 'HOME') }}/.fzf
    {{ lookup('env', 'HOME') }}/.fzf/install --all
  args:
    creates: "{{ lookup('env', 'HOME') }}/.fzf"
  when: fzf_version.rc !=0
  tags:
    - fzf
- name: Setup Ripgrep from Source 
  ansible.builtin.include_tasks: "setup_ripgrep_from_source.yml"
