- name: Install required packages 
  yum:
    name:
      - "@Development tools"
      - cmake
      - python3-devel
      - python3-pip
      - zsh
      - tmux
      - npm
      - gcc
      - g++
      - gdb
      - util-linux-user #chsh requires it
      - maven
    state: present
  become: yes
  tag: always
- name: Install boto3 with pip3
  pip:
    name: boto3
    executable: pip3
  become: yes
  tag: always
- name: Change shell to zsh
  user:
    name: "{{ ansible_env.USER }}"
    shell: /bin/zsh
  become: yes
  tag: always
- name: Setup Neovim from Source 
  ansible.builtin.include_tasks: "setup_nvim_from_source.yml"
  tag: always
- name: Setup fzf from Source 
  ansible.builtin.include_tasks: "setup_fzf_from_source.yml"
  tag: always
- name: Setup Ripgrep from Source 
  ansible.builtin.include_tasks: "setup_ripgrep_from_source.yml"
  tag: always
