---
- name: Configure global gitignore
  git_config:
    scope: global
    name: core.excludesfile
    value: "{{ config_path }}/dotfiles/gitignore_global"
  tags: always

- name: Check if configuration is cloned
  stat:
    path: "{{ lookup('env', 'HOME') }}/configurations"
  register: configuration_exists
  tags: always

- name: Clone configuration
  git:
    repo: git@github.com:waahm7/configurations.git
    dest: "{{ lookup('env', 'HOME') }}/configurations"
  when: configuration_exists.stat.exists == False
  tags: always
