- name: Check if fzf is already installed
  command: fzf --version
  register: fzf_version
  ignore_errors: yes
  changed_when: false
  tags: always
- name: Install fzf
  shell: |
    git clone --depth 1 https://github.com/junegunn/fzf.git {{ lookup('env', 'HOME') }}/.fzf
    {{ lookup('env', 'HOME') }}/.fzf/install --all
  args:
    creates: "{{ lookup('env', 'HOME') }}/.fzf"
  when: fzf_version.rc !=0
  tags: always

