- name: Check if ripgrep is already installed
  command: rg --version
  register: rg_version
  ignore_errors: yes
  changed_when: false
  tags: always
- name: Clone ripgrep repository
  git:
    repo: 'https://github.com/BurntSushi/ripgrep.git'
    dest: "/tmp/ripgrep"
    update: no
  when: rg_version.rc != 0
  tags: always
- name: Build ripgrep from source
  shell: |
    source $HOME/.cargo/env
    cd /tmp/ripgrep && cargo build --release
  args:
    creates: "/tmp/ripgrep/target/release/rg"
  when: rg_version.rc != 0
  tags: always
- name: Copy ripgrep binary to /usr/local/bin
  copy:
    src: "/tmp/ripgrep/target/release/rg"
    dest: /usr/local/bin/rg
    mode: '0755'
  when: rg_version.rc != 0
  become: yes
  tags: always
