- name: Check if Neovim is already installed
  command: nvim --version
  register: nvim_version
  ignore_errors: yes
  changed_when: false
  tags: always

- name: Download Neovim latest release
  get_url:
    url: https://github.com/neovim/neovim/releases/latest/download/nvim-linux-x86_64.tar.gz
    dest: /tmp/nvim-linux64.tar.gz
  when: nvim_version.rc != 0
  tags: always

- name: Remove existing Neovim installation
  file:
    path: /opt/nvim
    state: absent
  when: nvim_version.rc != 0
  become: yes
  tags: always

- name: Extract Neovim to /opt
  unarchive:
    src: /tmp/nvim-linux64.tar.gz
    dest: /opt
    remote_src: yes
  when: nvim_version.rc != 0
  become: yes
  tags: always

