---
- name: Configure global gitignore
  git_config:
    scope: global
    name: core.excludesfile
    value: "{{ config_path }}/dotfiles/gitignore_global"
  tags: 
    - git
- name: Git personal setup email
  git_config:
    name: user.email
    scope: global
    value: "waahm7@gmail.com"
  tags:
  - git
- name: Git personal setup name
  git_config:
    name: user.name
    scope: global
    value: "Waqar Ahmed Khan"
  tags:
  - git

# Clone the required repos, zsh plugins, packer, and tpm
- name: Clone configuration 
  git:
    repo: git@github.com:waahm7/configurations.git 
    dest: "{{ ansible_env.HOME }}/configurations"
  tags: 
    - git
    - dotfiles
    - install

- name: Clone zsh-syntax-highlighting
  git:
    repo: https://github.com/zsh-users/zsh-syntax-highlighting.git
    dest: "{{ ansible_env.HOME }}/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting"
  tags: 
    - zsh
    - git
    - install

- name: Clone zsh-autosuggestions
  git:
    repo: https://github.com/zsh-users/zsh-autosuggestions.git
    dest: "{{ ansible_env.HOME }}/.oh-my-zsh/custom/plugins/zsh-autosuggestions"
  tags: 
    - zsh
    - git
    - install

- name: Clone zsh-autocomplete
  git:
    repo: https://github.com/marlonrichert/zsh-autocomplete.git
    dest: "{{ ansible_env.HOME }}/.oh-my-zsh/custom/plugins/zsh-autocomplete"
    depth: 1
  tags: 
    - zsh
    - git
    - install

- name: Clone powerlevel10k
  git:
    repo: https://github.com/romkatv/powerlevel10k.git
    dest: "{{ ansible_env.HOME }}/.oh-my-zsh/custom/themes/powerlevel10k"
    depth: 1
  tags: 
    - zsh
    - git
    - install

- name: Clone ohmyzsh-full-autoupdate
  git:
    repo: https://github.com/Pilaton/OhMyZsh-full-autoupdate.git
    dest: "{{ ansible_env.HOME }}/.oh-my-zsh/custom/plugins/ohmyzsh-full-autoupdate"
  tags: 
    - zsh
    - git
    - install

- name: Install Neovim Packer
  git:
    repo: https://github.com/wbthomason/packer.nvim
    dest: ~/.local/share/nvim/site/pack/packer/start/packer.nvim
    depth: 1
  tags: 
    - neovim
    - git
    - install

- name: Install Tmux Plugin Manager
  git:
    repo: https://github.com/tmux-plugins/tpm
    dest: ~/.tmux/plugins/tpm
  tags: 
    - tmux
    - git
    - install
