---
- name: Configure global gitignore
  git_config:
    scope: global
    name: core.excludesfile
    value: "{{ config_path }}/dotfiles/gitignore_global"
  tags: always
# Clone the required repos, zsh plugins, and tpm
- name: Clone configuration
  git:
    repo: git@github.com:waahm7/configurations.git
    dest: "{{ lookup('env', 'HOME') }}/configurations"
  tags: always
#omz config
- name: Check if Oh-My-Zsh is installed
  stat:
    path: "{{ lookup('env', 'HOME') }}/.oh-my-zsh"
  register: oh_my_stats
  tags: always
- name: Install Oh-My-Zsh
  shell: |
    curl -L https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh > ~/.oh-my-installer &&
    chmod +x ~/.oh-my-installer &&
    ~/.oh-my-installer
  when: oh_my_stats.stat.exists == False
  tags: always
- name: Clone zsh-syntax-highlighting
  git:
    repo: https://github.com/zsh-users/zsh-syntax-highlighting.git
    dest: "{{ lookup('env', 'HOME') }}/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting"
  tags: always
- name: Clone zsh-autosuggestions
  git:
    repo: https://github.com/zsh-users/zsh-autosuggestions.git
    dest: "{{ lookup('env', 'HOME') }}/.oh-my-zsh/custom/plugins/zsh-autosuggestions"
  tags: always
- name: Clone zsh-autocomplete
  git:
    repo: https://github.com/marlonrichert/zsh-autocomplete.git
    dest: "{{ lookup('env', 'HOME') }}/.oh-my-zsh/custom/plugins/zsh-autocomplete"
    depth: 1
  tags: always
- name: Clone powerlevel10k
  git:
    repo: https://github.com/romkatv/powerlevel10k.git
    dest: "{{ lookup('env', 'HOME') }}/.oh-my-zsh/custom/themes/powerlevel10k"
    depth: 1
  tags: always
- name: Clone ohmyzsh-full-autoupdate
  git:
    repo: https://github.com/Pilaton/OhMyZsh-full-autoupdate.git
    dest: "{{ lookup('env', 'HOME') }}/.oh-my-zsh/custom/plugins/ohmyzsh-full-autoupdate"
  tags: always
- name: Clone fzf-tab 
  git:
    repo: https://github.com/Aloxaf/fzf-tab 
    dest: "{{ lookup('env', 'HOME') }}/.oh-my-zsh/custom/plugins/fzf-tab"
  tags: always
- name: Install Tmux Plugin Manager
  git:
    repo: https://github.com/tmux-plugins/tpm
    dest: "{{ lookup('env', 'HOME') }}/.tmux/plugins/tpm"
  tags: always

