- name: Check if neovim is already installed
  command: nvim --version
  register: nvim_version 
  ignore_errors: yes
  changed_when: false
  tags:
    - nvim 
- name: Upgrade pip and install Neovim package for Python
  pip:
    name: neovim
    state: latest
  tags:
    - nvim
- name: Clone Neovim repository
  git:
    repo: 'https://github.com/neovim/neovim.git'
    dest: '/tmp/neovim'
    update: no 
  when: nvim_version.rc != 0
  tags:
    - nvim
- name: Build Neovim from source
  command: make CMAKE_BUILD_TYPE=Release -j
  args:
    chdir: /tmp/neovim
  when: nvim_version.rc != 0
  tags:
    - nvim
- name: Install Neovim
  command: make install
  args:
    chdir: /tmp/neovim
    creates: /usr/local/bin/nvim
  when: nvim_version.rc != 0
  become: yes
  tags:
    - nvim

